package pt.isel.leic.multicloudguardian.http.media

import org.springframework.http.HttpStatus
import org.springframework.http.MediaType.APPLICATION_PROBLEM_JSON_VALUE
import org.springframework.http.ResponseEntity
import pt.isel.leic.multicloudguardian.domain.user.components.Email
import pt.isel.leic.multicloudguardian.domain.user.components.Username
import java.net.URI

/**
 *  Represents a problem in the API
 * @param type A URI reference that identifies the problem type.
 * @param title A short, human-readable summary of the problem type.
 * @param status The HTTP status code generated by the origin server for this occurrence of the problem.
 * @param detail Optional human-readable explanation specific to this occurrence of the problem.
 * @param instance Optional URI reference that identifies the specific occurrence of the problem.
 */
class Problem(
    val type: URI,
    val title: String,
    val status: Int,
    val detail: String,
    val instance: URI? = null,
) {
    fun toResponse() =
        ResponseEntity
            .status(status)
            .header("Content-Type", MEDIA_TYPE)
            .header("Content-Language", LANGUAGE)
            .body<Any>(this)

    companion object {
        const val MEDIA_TYPE = APPLICATION_PROBLEM_JSON_VALUE
        const val LANGUAGE = "en"

        private const val BASE_URL =
            "https://github.com/saraiva22/Multi-Cloud-Guardian/tree/main/code/backend/docs/problems/"
        private const val DEFAULT_FOLDER = BASE_URL + "default/"
        private const val USER_FOLDER = BASE_URL + "user/"
        private const val TOKEN_FOLDER = BASE_URL + "token/"
        private const val FILE_FOLDER = BASE_URL + "file/"

        fun response(
            status: Int,
            problem: Problem,
        ) = ResponseEntity
            .status(status)
            .header("Content-Type", MEDIA_TYPE)
            .header("Content-Language", LANGUAGE)
            .body<Any>(problem)

        // Default
        val internalServerError = URI("${DEFAULT_FOLDER}internal-server-error")
        val badRequest = URI("${DEFAULT_FOLDER}bad-request")
        val invalidRequestContent = URI("${DEFAULT_FOLDER}invalid-request-content")

        // User
        private val usernameAlreadyExists = URI("${USER_FOLDER}username-already-exists")
        private val emailAlreadyExists = URI("${USER_FOLDER}email-already-exists")
        private val invalidInviteCode = URI("${USER_FOLDER}invalid-register-code")
        private val userNotFound = URI("${USER_FOLDER}user-not-found")
        private val usernameNotFound = URI("${USER_FOLDER}username-not-found")
        private val invalidEmail = URI("${USER_FOLDER}invalid-email")
        private val insecurePassword = URI("${USER_FOLDER}insecure-password")
        private val userOrPasswordAreInvalid = URI("${USER_FOLDER}user-or-password-are-invalid")

        // Token
        private val invalidToken = URI("${TOKEN_FOLDER}user-not-found")
        private val tokenNotRevoked = URI("${TOKEN_FOLDER}token-not-revoked")
        val unauthorizedRequest = URI("${TOKEN_FOLDER}unauthorized")

        // File
        private val invalidCreateFile = URI("${FILE_FOLDER}invalid-create-file")

        fun internalServerError(instance: URI?): ResponseEntity<*> =
            Problem(
                type = internalServerError,
                title = "Internal server error",
                status = HttpStatus.INTERNAL_SERVER_ERROR.value(),
                detail = "An intervale server error occured",
                instance = instance,
            ).toResponse()

        fun invalidRequestContent(errors: List<String>? = null): Problem =
            Problem(
                type = invalidRequestContent,
                title = "Invalid request content",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = errors?.joinToString(", ") ?: "Invalid request content",
                instance = invalidRequestContent,
            )

        fun unauthorizedRequest(instance: URI?): ResponseEntity<*> =
            Problem(
                type = unauthorizedRequest,
                title = "Unauthorized Request",
                status = HttpStatus.UNAUTHORIZED.value(),
                detail = "The request has not been applied because it lacks valid authentication credentials for the target resource.",
                instance = instance,
            ).toResponse()

        fun insecurePassword(instance: URI?): ResponseEntity<*> =
            Problem(
                type = insecurePassword,
                title = "Insecure password",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Password is insecure",
                instance = instance,
            ).toResponse()

        fun invalidToken(instance: URI?): ResponseEntity<*> =
            Problem(
                type = invalidToken,
                title = "Invalid token",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Invalid token",
                instance = instance,
            ).toResponse()

        fun passwordDoesNotMatch(instance: URI?): ResponseEntity<*> =
            Problem(
                type = userOrPasswordAreInvalid,
                title = "Password does not match",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Password supplied does not match the user's password",
                instance = instance,
            ).toResponse()

        fun tokenNotRevoked(
            instance: URI?,
            token: String,
        ): ResponseEntity<*> =
            Problem(
                type = tokenNotRevoked,
                title = "Token not revoked",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Token $token not revoked",
                instance = instance,
            ).toResponse()

        fun userNotFound(
            id: Int,
            instance: URI?,
        ): ResponseEntity<*> =
            Problem(
                type = userNotFound,
                title = "User not found",
                status = HttpStatus.NOT_FOUND.value(),
                detail = "User with given id: $id not found",
                instance = instance,
            ).toResponse()

        fun usernameAlreadyExists(
            username: Username,
            instance: URI?,
        ): ResponseEntity<*> =
            Problem(
                type = usernameAlreadyExists,
                title = "UserName already exists",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Give username ${username.value} already exists",
                instance = instance,
            ).toResponse()

        fun usernameNotFound(
            username: String,
            instance: URI?,
        ): ResponseEntity<*> =
            Problem(
                type = usernameNotFound,
                title = "UserName not found",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Give username $username not found",
                instance = instance,
            ).toResponse()

        fun emailAlreadyExists(
            email: Email,
            instance: URI?,
        ): ResponseEntity<*> =
            Problem(
                type = emailAlreadyExists,
                title = "Email already exists",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Give emails ${email.value} already exists",
                instance = instance,
            ).toResponse()

        fun invalidEmail(
            email: Email,
            instance: URI?,
        ): ResponseEntity<*> =
            Problem(
                type = invalidEmail,
                title = "Invalid email",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Email is invalid",
                instance = instance,
            ).toResponse()

        fun invalidFileCreation(instance: URI?): ResponseEntity<*> =
            Problem(
                type = invalidCreateFile,
                title = "Invalid file creation",
                status = HttpStatus.BAD_REQUEST.value(),
                detail = "Invalid file creation",
                instance = instance,
            ).toResponse()
    }
}
