FROM postgres

USER postgres
WORKDIR /app
ARG REPO_PATH=multicloud-guardian/repository-jdbi/src/sql
ARG HOST_PATH=multicloud-guardian/host

COPY ${REPO_PATH}/create-schema.sql /docker-entrypoint-initdb.d/1_create.sql
COPY ${REPO_PATH}/insert-test-data.sql /docker-entrypoint-initdb.d/2_insert-test-data.sql

COPY --chown=postgres:postgres ${HOST_PATH}/tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432