services:
  multi-cloud-guardian-tests:
    container_name: mcg-postgres-tests
    image: multi-cloud-guardian-postgres-test
    build:
      context: ./
      dockerfile: ./tests/Dockerfile-postgres-test
    env_file:
      - ./.env
    ports:
      - 5432:5432

  multi-cloud-guardian-jvm:
    image: multi-cloud-guardian-jvm
    container_name: mcg-jvm
    hostname: mcg-dynamic
    build:
      context: ./
      dockerfile: ./tests/Dockerfile-jvm
    env_file:
      - ./.env
    volumes:
      - ./json-key.json:/app/creds/json-key.json:ro

  nginx:
    container_name: mcg-nginx
    image: multi-cloud-guardian-nginx
    build:
      context: ./
      dockerfile: ./tests/Dockerfile-nginx
    ports:
      - 8080:8080
      - 8088:8088
    depends_on:
      - multi-cloud-guardian-jvm

  ubuntu:
    container_name: ubuntu
    image: multi-cloud-guardian-ubuntu
    build:
      context: ./
      dockerfile: ./tests/Dockerfile-ubuntu
    tty: true
