name: Continuous Check

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Continuous Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./code/backend/gradlew
      - name: Build with Gradle
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: ./code/backend/gradlew -p code/backend check --info
