
name: Continuous Check

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Continuous Check
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./code/backend/gradlew
      - name: Build with Gradle
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: ./code/backend/gradlew -p code/backend check --info
