name: Continuous Check

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Continuous Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Build with Gradle
        env:
          DB_URL: jdbc:postgresql://localhost:5432/${{ secrets.POSTGRES_DB }}?user=${{ secrets.POSTGRES_USER }}&password=${{ secrets.POSTGRES_PASSWORD }}
        run: ./code/backend/gradlew -p code/backend check --info
